In [ ]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_breast_cancer         #load dataset from sklearn library
from sklearn.preprocessing import StandardScaler        #import standerdScaler function from sklearn

from keras.models import Sequential                     #import keras for making neural network
from keras.layers import Dense

In [ ]:
data = load_breast_cancer()

In [ ]:
data                                                    # all the data loaded in dictionary format

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For

In [ ]:
data.keys()                              #all the keys of dataset    

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [ ]:
dscr = data['DESCR']                    #description of dataset
print(dscr)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [ ]:
data['data'].shape                        #number of samples and parameters

(569, 30)

In [ ]:
data['feature_names']                   #all the parameters

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
data['data'][0]                    #to  get all the parameters value of any particular data

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [ ]:
j = 0
for i in data['feature_names']:
    print(i,':',data['data'][0][j])
    j += 1

mean radius : 17.99
mean texture : 10.38
mean perimeter : 122.8
mean area : 1001.0
mean smoothness : 0.1184
mean compactness : 0.2776
mean concavity : 0.3001
mean concave points : 0.1471
mean symmetry : 0.2419
mean fractal dimension : 0.07871
radius error : 1.095
texture error : 0.9053
perimeter error : 8.589
area error : 153.4
smoothness error : 0.006399
compactness error : 0.04904
concavity error : 0.05373
concave points error : 0.01587
symmetry error : 0.03003
fractal dimension error : 0.006193
worst radius : 25.38
worst texture : 17.33
worst perimeter : 184.6
worst area : 2019.0
worst smoothness : 0.1622
worst compactness : 0.6656
worst concavity : 0.7119
worst concave points : 0.2654
worst symmetry : 0.4601
worst fractal dimension : 0.1189


In [ ]:
data['target']                               #all the labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
data['target_names']                     #all the label name

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
feature = data['data']
label = data['target']

In [ ]:
feature.shape

(569, 30)

In [ ]:
label.shape

(569,)

In [ ]:
scale = StandardScaler()
feature = scale.fit_transform(feature)                   #standarize all the values of freature in data preprocessing

In [ ]:
feature[0]

array([ 1.09706398, -2.07333501,  1.26993369,  0.9843749 ,  1.56846633,
        3.28351467,  2.65287398,  2.53247522,  2.21751501,  2.25574689,
        2.48973393, -0.56526506,  2.83303087,  2.48757756, -0.21400165,
        1.31686157,  0.72402616,  0.66081994,  1.14875667,  0.90708308,
        1.88668963, -1.35929347,  2.30360062,  2.00123749,  1.30768627,
        2.61666502,  2.10952635,  2.29607613,  2.75062224,  1.93701461])

In [ ]:
label[0]

0

In [ ]:
print(feature[200])
print(data['target_names'][label][200])

[-0.53885779  0.06291261 -0.55314457 -0.55144051 -0.03560273 -0.44480987
 -0.5891962  -0.20246073  0.61109991 -0.37816145 -0.18685622  0.19802942
 -0.2762564  -0.28815813  0.15768009 -0.42968654 -0.59297079 -0.06425726
 -0.66742089 -0.1728245  -0.37879325  0.43687355 -0.45010014 -0.4257368
  0.46165357 -0.31848363 -0.64521166 -0.1005903  -0.37654768 -0.12223716]
benign


In [ ]:
df_frt = pd.DataFrame(feature,columns=data['feature_names'])             #convert feature into dataframe format
df_lbl = pd.DataFrame(label,columns=['label'])                            #convert label into dataframe
df = pd.concat([df_frt,df_lbl],axis=1)                                   #concatinate both
df = df.sample(frac = 1)                                                 #for shuffle the data 

feature = df.values[ : , : 30]                                             #for feature taking first 30 cloumn
label = df.values[ : , 30 : ]                                              #for label taking last cloumn      

In [ ]:
df.head()

mean radius  mean texture  ...  worst fractal dimension  label
305    -0.717787      1.210157  ...                -0.914129      1
54      0.276263      0.635371  ...                -0.289039      0
53      1.162387     -0.137215  ...                -0.225865      0
230     0.830091     -0.048787  ...                 0.369301      0
241    -0.484895     -0.988922  ...                -0.893071      1

[5 rows x 31 columns]

In [ ]:
# deviding the dataset into three parts training testing validation

# 500 samples for training
x_train = feature[:500]
y_train = label[:500]

# 35 samples for validation
x_val = feature[500:535]
y_val = label[500:535]

# 34 samples for testing
x_test = feature[535:]
y_test = label[535:]

In [ ]:
model = Sequential()                                     #creating empty stack/neural network

model.add(Dense(32, activation='relu', input_dim=30))       #creating frist hidden layer
model.add(Dense(64, activation = 'relu'))
model.add(Dense(128, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(32, activation = 'relu'))                      #rest hidden layer
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, batch_size=5, epochs=10, validation_data=(x_val,y_val))             #training and validating data

Epoch 1/10
100/100 [==============================] - 1s 3ms/step - loss: 0.2105 - accuracy: 0.9340 - val_loss: 0.0420 - val_accuracy: 0.9714
Epoch 2/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0824 - accuracy: 0.9780 - val_loss: 0.1061 - val_accuracy: 0.9429
Epoch 3/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0597 - accuracy: 0.9820 - val_loss: 0.0721 - val_accuracy: 0.9714
Epoch 4/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0521 - accuracy: 0.9840 - val_loss: 0.1551 - val_accuracy: 0.9143
Epoch 5/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0677 - accuracy: 0.9780 - val_loss: 0.0457 - val_accuracy: 1.0000
Epoch 6/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0296 - accuracy: 0.9920 - val_loss: 0.0767 - val_accuracy: 0.9429
Epoch 7/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0240 - accuracy: 0.9920 - val_loss: 0.1774 - val_accuracy: 0.9143
Epoch 

In [ ]:
model.evaluate(x_test,y_test)                        #testing data

2/2 [==============================] - 0s 5ms/step - loss: 0.0014 - accuracy: 1.0000


[0.0014445792185142636, 1.0]

In [ ]:
model.evaluate(x_val,y_val)    

2/2 [==============================] - 0s 4ms/step - loss: 0.1439 - accuracy: 0.9429


[0.14387299120426178, 0.9428571462631226]

In [ ]:
for i in range(10):
  sample = x_test[i]
  sample = np.reshape(sample,(1,30))                                 #reshape the sample
  #predicted value
  if (model.predict(sample)[0][0] > 0.5):
    print("-Benign")
  else:
    print("-malignant")
  #actual value
  if (y_test[i] == 1):
    print("*Benign")
  else:
    print("*malignant")

  print("********")

-malignant
*malignant
********
-Benign
*Benign
********
-Benign
*Benign
********
-malignant
*malignant
********
-Benign
*Benign
********
-malignant
*malignant
********
-malignant
*malignant
********
-malignant
*malignant
********
-Benign
*Benign
********
-Benign
*Benign
********
